'use client'

import { useLocale } from 'next-intl'
import { Button } from '@/src/components/ui/button'
import { Icon } from '@/src/components/ui/icons'
import type { WorkspaceController } from './use-workspace-controller'

export function EditorDialog({ controller }: { controller: WorkspaceController }) {
  const locale = useLocale()
  const isChinese = locale === 'zh'
  const item = controller.items.find((candidate) => candidate.id === controller.editingItemId)
  if (!item?.resultUrl) return null
  const { editState } = controller
  return <div className="editor-backdrop" onClick={() => controller.setEditingItemId(null)}><div className="editor-dialog" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><div className="editor-header"><div><span className="kicker">{isChinese ? '编辑结果' : 'Edit result'}</span><h2>{isChinese ? '编辑处理后的图片' : 'Edit processed image'}</h2><p className="editor-subtitle">{isChinese ? '裁剪、旋转、翻转并选择导出质量。' : 'Crop, rotate, flip, and choose export quality.'}</p></div><Button variant="ghost" size="icon" onClick={() => controller.setEditingItemId(null)} aria-label={isChinese ? '关闭' : 'Close'}><Icon name="close" /></Button></div><div className="editor-preview"><img src={item.resultUrl} alt={isChinese ? '增强预览' : 'Enhanced preview'} style={{ transform: `rotate(${editState.rotation}deg) scaleX(${editState.flipX ? -1 : 1}) scaleY(${editState.flipY ? -1 : 1})` }} /></div><div className="editor-controls"><div className="editor-tool-row"><Button variant="outline" size="sm" onClick={() => controller.setEditState({ ...editState, rotation: (editState.rotation + 90) % 360 })}><Icon name="rotate" />{isChinese ? '旋转' : 'Rotate'}</Button><Button variant={editState.flipX ? 'default' : 'outline'} size="sm" onClick={() => controller.setEditState({ ...editState, flipX: !editState.flipX })}><Icon name="flip" />{isChinese ? '水平翻转' : 'Flip horizontal'}</Button><Button variant={editState.flipY ? 'default' : 'outline'} size="sm" onClick={() => controller.setEditState({ ...editState, flipY: !editState.flipY })}><Icon name="flip" />{isChinese ? '垂直翻转' : 'Flip vertical'}</Button></div><label>{isChinese ? '裁剪比例' : 'Crop ratio'}<select value={editState.crop} onChange={(event) => controller.setEditState({ ...editState, crop: event.target.value as typeof editState.crop })}><option value="original">{isChinese ? '原始比例' : 'Original'}</option><option value="square">1:1 {isChinese ? '方形' : 'Square'}</option><option value="4:3">4:3</option><option value="16:9">16:9</option></select></label><div className="editor-export-grid"><label>{isChinese ? '格式' : 'Format'}<select value={editState.format} onChange={(event) => controller.setEditState({ ...editState, format: event.target.value as typeof editState.format })}><option value="webp">WebP</option><option value="png">PNG</option><option value="jpeg">JPG</option></select></label><label>{isChinese ? '质量' : 'Quality'}：{editState.quality}%<input type="range" min="60" max="100" value={editState.quality} onChange={(event) => controller.setEditState({ ...editState, quality: Number(event.target.value) })} /></label></div><div className="editor-footer-actions"><Button variant="ghost" onClick={() => controller.setEditingItemId(null)}>{isChinese ? '取消' : 'Cancel'}</Button><Button onClick={controller.saveEdit}>{isChinese ? '保存更改' : 'Save changes'} <Icon name="check" /></Button></div></div></div></div>
}
