import type { Locale } from './locale'

export type LegalContent = { title: string; intro: string; sections: readonly [string, string][] }

export const legalContent: Record<'privacy-policy' | 'terms' | 'cookies', Record<Locale, LegalContent>> = {
  'privacy-policy': {
    zh: { title: '隐私政策', intro: 'ImgUpscaler 是由 Sparklightforce Limited 运营的在线 AI 图像放大与增强服务。本页面说明我们如何收集、使用和保护您在使用服务时提供的信息。', sections: [['1. 我们收集的信息', '为提供和改进 ImgUpscaler，我们可能收集电子邮件、账户名称、头像、登录方式、上传图片、生成结果、账单状态、积分余额、使用记录、设备和浏览器信息、IP 地址、Cookies 以及您发送的客服消息。'], ['2. 信息的使用方式', '我们使用这些信息来运行图像处理流程、创建和管理账户、验证身份、提供积分和账单功能、防止滥用、处理客服请求、改进服务可靠性、衡量产品性能并履行法律义务。我们不会出售您的个人信息。'], ['3. 上传图片与生成结果', '上传的图片仅用于提供放大、增强、预览和下载功能。生产服务中的源图和结果不会作为长期资产保存，处理完成后会在 24 小时内自动删除。当前前端演示只在浏览器内生成本地预览。'], ['4. Cookies 与分析', '我们可能使用 Cookies 保存登录状态、偏好设置、服务安全信息并分析流量。接入分析或广告服务时，相关供应商会依据其隐私政策和适用法律处理有限的使用数据。'], ['5. 安全与保留', '我们会采取合理的技术和组织措施保护信息。账户、账单和使用记录仅在提供服务、解决争议、防止滥用及满足法律义务所需期间保留。'], ['6. 您的选择', '您可以联系 support@imgupscaler.com 请求访问、更正或删除账户信息，也可以通过浏览器设置管理 Cookies。禁用必要 Cookies 可能导致部分功能无法使用。'], ['7. 联系我们', '如对本隐私政策有疑问，请发送邮件至 support@imgupscaler.com。Sparklightforce Limited：ROOM 1503-09, 15/F, CAUSEWAY BAY CENTRE, 15-23 SUGAR STREET, CAUSEWAY BAY, HONG KONG。']] },
    en: { title: 'Privacy Policy', intro: 'ImgUpscaler is an online AI image upscaling and enhancement service operated by Sparklightforce Limited. This page explains the information we collect, how we use it, and your choices.', sections: [['1. Information We Collect', 'We may collect your email address, account name, profile image, authentication provider, uploaded images, generated results, billing status, credit balance, usage history, device and browser information, IP address, cookies, and support messages.'], ['2. How We Use Information', 'We use information to operate image processing, manage accounts, authenticate users, provide credits and billing, prevent abuse, answer support requests, improve reliability, measure product performance, and comply with legal obligations. We do not sell personal information.'], ['3. Uploaded Images and Generated Results', 'Images are processed to provide upscaling, enhancement, preview, and download features. Production uploads and results are automatically removed within 24 hours after processing. This demo generates previews in the browser.'], ['4. Cookies and Analytics', 'Cookies may keep users signed in, remember preferences, protect the service, analyze traffic, and improve performance. Analytics and advertising partners may process limited usage data under their own policies and applicable law.'], ['5. Security and Retention', 'We use reasonable technical and organizational safeguards. Account, billing, and usage records are retained only as needed to provide the service, resolve disputes, prevent abuse, and meet legal obligations.'], ['6. Your Choices', 'You may contact support@imgupscaler.com to request access, correction, or deletion of account information. You can manage cookies through your browser settings, though required features may stop working.'], ['7. Contact Us', 'Questions about this policy can be sent to support@imgupscaler.com. Sparklightforce Limited: ROOM 1503-09, 15/F, CAUSEWAY BAY CENTRE, 15-23 SUGAR STREET, CAUSEWAY BAY, HONG KONG.']] },
  },
  terms: {
    zh: { title: '服务条款', intro: '使用 ImgUpscaler 即表示您同意遵守以下服务条款。正式上线前，请根据实际模型、积分、支付和内容安全策略进行法律审查。', sections: [['1. 服务范围', 'ImgUpscaler 提供在线图像放大、图像增强和 Reimagine AI 工作流。功能、模型、处理上限和可用地区可能随产品迭代而调整。'], ['2. 用户内容', '您必须拥有上传图片的必要权利，或已取得处理该图片的授权。不得上传违法、侵权、恶意或包含未经授权个人信息的内容。'], ['3. 演示限制', '当前复刻版本使用浏览器 Canvas 生成演示结果，不代表真实 AI 输出、商业授权、准确性或服务等级。'], ['4. 积分与订阅', '生产服务中的积分扣减、订阅、退款和账单状态应以账户页面与支付服务商记录为准。免费或付费生成结果是否适合商业项目，仍取决于原始素材权利和适用法律。'], ['5. 可接受使用', '不得尝试绕过额度、滥用批处理、干扰服务、反向攻击模型或将服务用于违法用途。我们可以为安全、维护或法律原因暂停相关任务。'], ['6. 联系方式', '如需帮助，请联系 support@imgupscaler.com。']] },
    en: { title: 'Terms of Service', intro: 'Using ImgUpscaler means you agree to these service terms. Review and adapt them with legal counsel before launching production billing or model services.', sections: [['1. Service Scope', 'ImgUpscaler provides online image upscaling, enhancement, and Reimagine AI workflows. Features, models, limits, and availability may change as the product evolves.'], ['2. User Content', 'You must own or have permission to process every image you upload. Do not upload unlawful, infringing, harmful, or unauthorized personal content.'], ['3. Demo Limitations', 'This clone uses browser Canvas processing for interaction demos. It does not represent real AI output, commercial authorization, accuracy, or a production service level.'], ['4. Credits and Subscriptions', 'In production, credits, subscriptions, refunds, and billing status are governed by the account page and payment provider records. Commercial use still depends on source-image rights and applicable law.'], ['5. Acceptable Use', 'Do not bypass limits, abuse batch processing, interfere with the service, attack models, or use the service unlawfully. We may pause tasks for safety, maintenance, or legal reasons.'], ['6. Contact', 'For help, email support@imgupscaler.com.']] },
  },
  cookies: {
    zh: { title: 'Cookie 政策', intro: 'Cookies 是保存在设备上的小型文本文件。本页面说明登录、偏好、分析与广告场景下可能使用的 Cookies，以及您可以进行的选择。', sections: [['1. 必要 Cookies', '这些 Cookies 用于保持登录状态、保存安全设置和完成核心功能，通常无法在系统中关闭。'], ['2. 性能与功能 Cookies', '性能 Cookies 帮助我们了解访问者如何使用服务；功能 Cookies 用于记住语言和其他偏好。'], ['3. 第三方 Cookies', '分析、广告、支付和登录供应商可能设置第三方 Cookies，并依据其自己的隐私政策处理数据。'], ['4. 您的选择', '您可以通过浏览器设置删除或阻止 Cookies。禁用必要 Cookies 可能导致登录、上传或结账功能无法正常工作。'], ['5. 联系我们', '如需了解 Cookies 的使用情况，请联系 support@imgupscaler.com。']] },
    en: { title: 'Cookies', intro: 'Cookies are small text files stored on your device. This page explains how cookies may support sign-in, preferences, analytics, and advertising, along with your choices.', sections: [['1. Essential Cookies', 'Essential cookies keep sessions active, preserve security settings, and support core functionality. They generally cannot be disabled in our systems.'], ['2. Performance and Functional Cookies', 'Performance cookies help us understand how visitors use the service. Functional cookies remember language and other preferences.'], ['3. Third-Party Cookies', 'Analytics, advertising, payment, and authentication providers may set third-party cookies under their own privacy policies.'], ['4. Your Choices', 'You can delete or block cookies in your browser. Disabling required cookies may prevent sign-in, uploads, or checkout from working correctly.'], ['5. Contact', 'Questions about cookie usage can be sent to support@imgupscaler.com.']] },
  },
}

