'use client'

import { useState } from 'react'
import { useLocale } from 'next-intl'
import { Icon } from '@/src/components/ui/icons'
import type { Route } from '@/src/lib/types'

type PlanId = 'free' | 'premium' | 'business'
type Locale = 'zh' | 'en'
type PricingPlan = { id: PlanId; name: string; monthly: string; annual: string; label: string; description: string; features: string[]; featured: boolean; highlight?: string; action: string; footnote?: string }
type PricingCopy = {
  title: string; description: string; monthly: string; annual: string; annualBadge: string; popular: string; annualPrice: string; billingNote: string
  valueTitle: string; valueDescription: string; benefits: readonly [string, string][]; faqKicker: string; faqTitle: string; faqEmphasis: string; faqDescription: string
  plans: PricingPlan[]; faqs: readonly [string, string][]
}

const pricingCopy: Record<Locale, PricingCopy> = {
  zh: {
    title: '选择适合您图像工作流的套餐', description: 'ImgUpscaler 和 Reimagine 可免费使用。当您需要更多积分、批量处理或更高处理量时再升级。', monthly: '每月', annual: '每年', annualBadge: '最佳价值', popular: '推荐', annualPrice: '/月 · 按年计费', billingNote: '安全结算。您可随时在账户账单页面取消订阅。', valueTitle: '为何升级物有所值', valueDescription: '付费套餐专为需要更大处理能力、更高效的工作流程以及更清晰图像效果的用户设计，适用于实际项目，而不仅仅是偶尔的测试。',
    benefits: [['更多创作空间', '在 AI 图像放大、照片增强及 Reimagine AI 功能中使用更多积分，且不触及免费套餐的上限。'], ['批量工作流', '无论您是在准备电商照片、社交媒体素材、AI 艺术作品、人像照片还是客户交付物，都能更快地处理多张图片。'], ['高级创意工具', '升级以获取更高容量的增强工作流、Reimagine AI 功能以及更清晰的商业级输出效果。'], ['付费套餐无广告', '通过更简洁的工作区和更少的干扰，让您专注于图像编辑和导出。'], ['安全计费', '结账流程通过安全的支付服务商处理，您可通过账户管理套餐变更。'], ['专为商业用途打造', '为产品列表、广告、作品集、社交媒体帖子、演示文稿及客户项目制作更高质量的视觉素材。']],
    faqKicker: '定价常见问题解答', faqTitle: '关于积分、计费周期与', faqEmphasis: '套餐升级。', faqDescription: '关于积分、计费周期、套餐升级、结账流程以及如何选择合适的 ImgUpscaler 套餐的常见问题。',
    plans: [
      { id: 'free', name: '免费', monthly: '$0', annual: '$0', label: '先试用一下', description: '最适合用于测试 AI 图像放大功能，并每月优化少量图片。', features: ['每月 50 积分', '无需订阅', '试用 AI 图像放大与增强功能', '可使用 Reimagine AI', '单张图片处理', '包含广告'], featured: false, action: '立即免费试用', footnote: '无需付费订阅。' },
      { id: 'premium', name: '高级版', monthly: '$9.90', annual: '$6.14', label: '最受欢迎', description: '特别适合经常需要优化图片的创作者、营销人员和小团队。', features: ['每月 500 积分', '电子邮件支持', '可使用 Reimagine AI', '批量处理', '无广告', '最适合普通创作者的选择'], featured: true, highlight: '每月 500 积分', action: '选择高级版' },
      { id: 'business', name: '商业版', monthly: '$19.90', annual: '$12.34', label: '适用于高容量', description: '适用于需要高处理量的企业及生产工作流。', features: ['无积分限制', '电子邮件支持', '单张和批量处理', '可使用 Reimagine AI', '无广告', '最适合商业及高使用量场景'], featured: false, highlight: '无积分限制', action: '选择商业版' },
    ],
    faqs: [['我应该选择哪个套餐？', '若仅需测试 ImgUpscaler，请选择“免费”套餐。若您经常进行图像增强且需要批量处理、更多积分、Reimagine AI 功能以及无广告体验，请选择“高级版”套餐。若您因频繁进行商业或生产工作而需要无积分限制，请选择“商业版”套餐。'], ['积分能让我做什么？', '积分用于 AI 处理任务，例如图像放大、图像增强及相关创意工作流程。付费套餐提供更多循环处理额度，让您在每个计费周期内能够处理更多图像。'], ['我可以随时取消订阅吗？', '是的。您可以在账户计费页面取消订阅。您的访问权限和积分将保留至当前计费周期结束。'], ['如果积分用完了，如何获取更多积分？', '升级至更高阶套餐即可获得更大的定期额度。如果您经常处理图像集或使用 Reimagine AI，高级版或商业版套餐通常更合适。'], ['在这个网站上付款安全吗？', '是的。支付处理由安全的支付服务商负责，交易均经过加密处理。'], ['我以后可以升级或降级套餐吗？', '是的。您可以随时通过账户中的“计费”部分更改套餐。'], ['如果付款失败，我该怎么办？', '请通过 support@imgupscaler.com 联系客服，并提供账户邮箱及大致付款时间，以便我们及时为您提供帮助。'], ['我的订阅费用何时收取？', '您的订阅将在每个计费周期（按月或按年）的同一天自动续订，该日期即为您最初的购买日期。'], ['我可以将处理结果用于商业项目吗？', '可以。免费或付费生成的结果均可用于个人和商业项目，但需遵守适用法律及原始图片的相关权利。']],
  },
  en: {
    title: 'Choose a plan for your image workflow', description: 'ImgUpscaler and Reimagine are free to try. Upgrade when you need more credits, batch processing, or higher volume.', monthly: 'Monthly', annual: 'Yearly', annualBadge: 'Best value', popular: 'Most popular', annualPrice: '/mo · billed yearly', billingNote: 'Secure checkout. Cancel anytime from your account billing page.', valueTitle: 'Why upgrading pays off', valueDescription: 'Paid plans are designed for real projects that need more processing power, a faster workflow, and clearer image output—not just occasional tests.',
    benefits: [['More room to create', 'Use more credits across AI upscaling, photo enhancement, and Reimagine AI without reaching the free-plan limit.'], ['Batch workflows', 'Process ecommerce photos, social assets, AI art, portraits, or client deliverables faster in one consistent workflow.'], ['Advanced creative tools', 'Unlock higher-volume enhancement workflows, Reimagine AI, and clearer commercial-ready output.'], ['Ad-free paid plans', 'Keep your workspace focused on editing and exporting with fewer distractions.'], ['Secure billing', 'Checkout is handled by a secure payment provider, while plan changes stay available in your account.'], ['Built for business work', 'Create higher-quality visuals for product listings, ads, portfolios, social posts, presentations, and client projects.']],
    faqKicker: 'Pricing FAQs', faqTitle: 'Questions about credits, billing, and', faqEmphasis: 'plan upgrades.', faqDescription: 'Answers about credits, billing cycles, plan changes, checkout, and choosing the right ImgUpscaler plan.',
    plans: [
      { id: 'free', name: 'Free', monthly: '$0', annual: '$0', label: 'Start here', description: 'Best for trying AI upscaling and improving a small number of images each month.', features: ['50 credits / month', 'No subscription required', 'Try AI upscaling and enhancement', 'Reimagine AI access', 'Single-image processing', 'Includes ads'], featured: false, action: 'Try for free', footnote: 'No paid subscription required.' },
      { id: 'premium', name: 'Premium', monthly: '$9.90', annual: '$6.14', label: 'For regular creators', description: 'A strong fit for creators, marketers, and small teams that improve images often.', features: ['500 credits / month', 'Email support', 'Reimagine AI access', 'Batch processing', 'Ad-free workspace', 'Best for everyday creators'], featured: true, highlight: '500 credits / month', action: 'Choose Premium' },
      { id: 'business', name: 'Business', monthly: '$19.90', annual: '$12.34', label: 'For higher volume', description: 'Built for businesses and production workflows that need more processing capacity.', features: ['Unlimited credits', 'Email support', 'Single and batch processing', 'Reimagine AI access', 'Ad-free workspace', 'Best for business volume'], featured: false, highlight: 'Unlimited credits', action: 'Choose Business' },
    ],
    faqs: [['Which plan should I choose?', 'Choose Free if you are only testing ImgUpscaler. Choose Premium if you enhance images regularly and need batch processing, more credits, Reimagine AI, and an ad-free workspace. Choose Business when commercial or production work requires unlimited credits.'], ['What can credits be used for?', 'Credits are used for AI processing tasks such as upscaling, enhancement, and related creative workflows. Paid plans provide more recurring capacity for each billing cycle.'], ['Can I cancel anytime?', 'Yes. You can cancel from the account billing page. Access and credits remain available until the current billing cycle ends.'], ['How can I get more credits?', 'Upgrade to a higher plan for a larger recurring allowance. Premium or Business is usually a better fit for image sets or frequent Reimagine AI use.'], ['Is payment secure?', 'Yes. Payment processing is handled by a secure provider and transactions are encrypted.'], ['Can I upgrade or downgrade later?', 'Yes. You can change your plan at any time from the Billing section of your account.'], ['What should I do if payment fails?', 'Contact support@imgupscaler.com with your account email and approximate payment time so the team can help.'], ['When am I charged?', 'Your subscription renews automatically on the same day of each monthly or yearly billing cycle, based on your original purchase date.'], ['Can I use results commercially?', 'Yes. Free and paid outputs can be used for personal and commercial projects, subject to applicable law and rights to the source images.']],
  },
}

export function PricingPage({ onChoose, onLogin }: { onChoose: (route: Route) => void; onLogin: () => void }) {
  const [annual, setAnnual] = useState(false)
  const [faqOpen, setFaqOpen] = useState<number | null>(null)
  const locale = (useLocale() || 'zh') as Locale
  const copy = pricingCopy[locale]
  const choosePlan = (plan: PricingPlan) => plan.id === 'free' ? onChoose('home') : onLogin()

  return <main className="pricing-page"><section className="pricing-hero section-wrap"><h1>{copy.title}</h1><p>{copy.description}</p><div className="billing-toggle"><button type="button" className={!annual ? 'active' : ''} aria-pressed={!annual} onClick={() => setAnnual(false)}>{copy.monthly}</button><button type="button" className={annual ? 'active' : ''} aria-pressed={annual} onClick={() => setAnnual(true)}>{copy.annual} <span>{copy.annualBadge}</span></button></div></section><section className="plans-grid section-wrap">{copy.plans.map((plan) => <article className={plan.featured ? 'plan-card featured' : 'plan-card'} key={plan.id}>{plan.featured && <span className="popular-badge">{copy.popular}</span>}<span className="plan-label">{plan.label}</span><h2>{plan.name}</h2><div className="plan-price">{annual ? plan.annual : plan.monthly}<small>{annual ? copy.annualPrice : '/mo'}</small></div>{plan.highlight && <p className="plan-highlight">{plan.highlight}</p>}<p className="plan-description">{plan.description}</p><ul>{plan.features.map((feature) => <li key={feature}><Icon name="check" />{feature}</li>)}</ul><button type="button" className={plan.featured ? 'dark-button full' : 'outline-button full'} onClick={() => choosePlan(plan)}>{plan.action} <Icon name="arrow" /></button>{plan.footnote && <p className="plan-footnote">{plan.footnote}</p>}</article>)}<p className="billing-note">{copy.billingNote}</p></section><section className="pricing-note section-wrap"><div><span className="feature-icon"><Icon name="lock" /></span><h2>{copy.valueTitle}</h2></div><p>{copy.valueDescription}</p></section><section className="pricing-benefits section-wrap">{copy.benefits.map(([title, description]) => <article key={title}><h3>{title}</h3><p>{description}</p></article>)}</section><section className="pricing-faq section-wrap"><div className="section-heading compact"><div><span className="kicker">{copy.faqKicker}</span><h2>{copy.faqTitle}<br /><em>{copy.faqEmphasis}</em></h2></div><p>{copy.faqDescription}</p></div><div className="faq-list">{copy.faqs.map(([question, answer], index) => { const expanded = faqOpen === index; const answerId = `pricing-faq-answer-${index}`; return <article className={expanded ? 'faq-item expanded' : 'faq-item'} key={question}><button type="button" aria-expanded={expanded} aria-controls={answerId} onClick={() => setFaqOpen(expanded ? null : index)}><span>{String(index + 1).padStart(2, '0')}</span><strong>{question}</strong><Icon name="chevron" /></button><p id={answerId} hidden={!expanded}>{answer}</p></article> })}</div></section></main>
}
